package com.example.hesz.labproject;

/**
 * Created by gergelyhesz on 08/01/2018.
 */

public class Content {
    public static final String nodes = "[{\"nodelist\":\"adev[0-1]\",\"nodes\":\"2\",\"partition\":\"debug\",\"state\":\"idle\",\"cpus\":\"2\",\"memory\":\"3448\",\"tmpdisk\":\"38536\",\"weight\":\"16\"},{\"nodelist\":\"adev[2,4-7]\",\"nodes\":\"5\",\"partition\":\"debug\",\"state\":\"idle\",\"cpus\":\"2\",\"memory\":\"3448\",\"tmpdisk\":\"38536\",\"weight\":\"16\"},{\"nodelist\":\"adev3\",\"nodes\":\"1\",\"partition\":\"debug\",\"state\":\"allocated\",\"cpus\":\"2\",\"memory\":\"3384\",\"tmpdisk\":\"38536\",\"weight\":\"16\"},{\"nodelist\":\"adev[8-9]\",\"nodes\":\"2\",\"partition\":\"batch\",\"state\":\"allocated\",\"cpus\":\"2\",\"memory\":\"3384\",\"tmpdisk\":\"82306\",\"weight\":\"16\"},{\"nodelist\":\"adev[10-15]\",\"nodes\":\"6\",\"partition\":\"batch\",\"state\":\"drain\",\"cpus\":\"2\",\"memory\":\"246\",\"tmpdisk\":\"82306\",\"weight\":\"16\"}]";
    public static final String partitions = "[{\"partition\":\"batch\",\"avail\":\"up\",\"timelimit\":\"infinite\",\"nodes\":\"2\\/6\\/0\\/8\",\"nodelist\":\"adev[8-15]\"},{\"partition\":\"debug\",\"avail\":\"up\",\"timelimit\":\"30:00\",\"nodes\":\"0\\/8\\/0\\/8 \",\"nodelist\":\"adev[0-7]\"},{\"partition\":\"part3\",\"avail\":\"down\",\"timelimit\":\"30:00\",\"nodes\":\"0\\/0\\/0\\/0 \",\"nodelist\":\"null\"},{\"partition\":\"part4\",\"avail\":\"down\",\"timelimit\":\"infinite\",\"nodes\":\"0\\/0\\/0\\/0\",\"nodelist\":\"null\"}]";
    public static final String jobs = "[{\"jobid\":\"3456\",\"partition\":\"debug\",\"name\":\"Job 1 name\",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev0\"},{\"jobid\":\"234532\",\"partition\":\"batch\",\"name\":\"Job 2 name \",\"user\":\"user 1\",\"status\":\"pending\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"5464342\",\"partition\":\"debug\",\"name\":\"Job 3 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"2342564\",\"partition\":\"debug\",\"name\":\"Job 4 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"42345\",\"partition\":\"batch\",\"name\":\"Job 5 name \",\"user\":\"user 1\",\"status\":\"pendig\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"231315\",\"partition\":\"debug\",\"name\":\"Job 6 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"432432\",\"partition\":\"debug\",\"name\":\"Job 7 name \",\"user\":\"user 1\",\"status\":\"pending\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"73845234\",\"partition\":\"batch\",\"name\":\"Job 8 name \",\"user\":\"user 1\",\"status\":\"completed\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"243235\",\"partition\":\"debug\",\"name\":\"Job 9 name \",\"user\":\"user 1\",\"status\":\"completed\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"123235\",\"partition\":\"batch\",\"name\":\"Job 10 name \",\"user\":\"user 1\",\"status\":\"failed\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"123123\",\"partition\":\"debug\",\"name\":\"Job 11 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"934232\",\"partition\":\"batch\",\"name\":\"Job 12 name \",\"user\":\"user 1\",\"status\":\"cancelled\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"324543\",\"partition\":\"debug\",\"name\":\"Job 13 name \",\"user\":\"user 1\",\"status\":\"completed\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"34557342\",\"partition\":\"batch\",\"name\":\"Job 14 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"},{\"jobid\":\"234235\",\"partition\":\"batch\",\"name\":\"Job 15 name \",\"user\":\"user 1\",\"status\":\"running\",\"time\":\"1-20:51:21\",\"nodes\":\"1\",\"nodelist\":\"adev\"}]";
}
